# Regularly update the token via the RetrieveToken.http script
@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IjE4ZDRiMmVmOGIxYzE0ODcwOTgzMmI3ZTNkMzNmNzMxIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NDMwNjEzMTcsImV4cCI6MTU0MzE0NzcxNywiaXNzIjoiaHR0cHM6Ly90dC1pZGVudGl0eXNlcnZlcjQtZGVtby5henVyZXdlYnNpdGVzLm5ldCIsImF1ZCI6WyJodHRwczovL3R0LWlkZW50aXR5c2VydmVyNC1kZW1vLmF6dXJld2Vic2l0ZXMubmV0L3Jlc291cmNlcyIsImFwaSJdLCJjbGllbnRfaWQiOiJyZXNvdXJjZW93bmVyIiwic3ViIjoiODg0MjExMTMiLCJhdXRoX3RpbWUiOjE1NDMwNjEzMTcsImlkcCI6ImxvY2FsIiwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsImFwaSJdLCJhbXIiOlsicHdkIl19.edUfU8t8K712AtazMJ9XDu6bA2BMrl2YGOVWpnG--BQobwHd-xT3IEk1itfPGpGnMZdgti-7oQqqqOgaHFJ4_sMjqdsVCV7_Z03D0GUIpaGfcrpPl4FeTHs47X9kAccsi409uclONtxUzXlGiPUQ6YyVA9tRej8gk8MkBB6ahAE4TXfVX2gFL8vYo2JshVnInhxRSaYreLWeC8ck6r1dMcwfJni4vSOkc-PVfRc8C8H7bcARgTVg_qgAnpdUb9Ic1jyttZe8xVoInfoUGpa0pSbY6RQz2fJq1SrjnZLghKXSNnnTzbtZQlYVoISMTyBoUrOhHmxvTUMkkt2hWgDOjQ

#GET http://localhost:7071/api/orders
#GET https://orders.serverlessmicroservices.net/api/orders
GET http://cw-serverless-microservices-orders.azurewebsites.net/api/orders
Content-Type: application/json
Authorization: Bearer {{ token }}
