# Regularly update the token via the RetrieveToken.http script
@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IjljNTIxMGFiZWZmZTg2ZjlkMmI5ZTEzM2Q4NWNjZDA4IiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NDcyOTIwNDYsImV4cCI6MTU0NzM3ODQ0NiwiaXNzIjoiaHR0cHM6Ly90dC1pZGVudGl0eXNlcnZlcjQtZGVtby5henVyZXdlYnNpdGVzLm5ldCIsImF1ZCI6WyJodHRwczovL3R0LWlkZW50aXR5c2VydmVyNC1kZW1vLmF6dXJld2Vic2l0ZXMubmV0L3Jlc291cmNlcyIsImFwaSJdLCJjbGllbnRfaWQiOiJyZXNvdXJjZW93bmVyIiwic3ViIjoiODg0MjExMTMiLCJhdXRoX3RpbWUiOjE1NDcyOTIwNDYsImlkcCI6ImxvY2FsIiwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsImFwaSJdLCJhbXIiOlsicHdkIl19.rNyac8gy4I-E1E9O4sDcRuhv3Q6lSx3X7zJy261BjubD1E_07C9dz9w9Yw9mxQhK6wGCDjoVO8Tlf44QuU_b5D_UAEqMdMayeJL77J-HqLB79wI17FnxGWBN21XiU3VgVXP7aaXTk4gjHzzldvAy-nFh1MSzdNmgM_mExq1PoG39L7EFvYIcxZMTvleHlmXEy2tVXk-YwlmEWg-FvnKUuhGuEf0b_KxezxaqvCCpv19BWYCq82cqZKhBVEoJBJaaAs0HfXOYfYcp671i_8fiWWfuKhBnRgIdyUQ1U6ixTZBdHfhwEGdxLz1v61D63rxGZjDE_qXSM7W_D6BJbv_iSQ

GET http://localhost:7071/api/orders
#GET https://orders.serverlessmicroservices.net/api/orders
#GET http://cw-serverless-microservices-orders.azurewebsites.net/api/orders
Content-Type: application/json
Authorization: Bearer {{ token }}
