# Regularly update the token via the RetrieveToken.http script
@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IjE4ZDRiMmVmOGIxYzE0ODcwOTgzMmI3ZTNkMzNmNzMxIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NDQ0NjcxNDUsImV4cCI6MTU0NDU1MzU0NSwiaXNzIjoiaHR0cHM6Ly90dC1pZGVudGl0eXNlcnZlcjQtZGVtby5henVyZXdlYnNpdGVzLm5ldCIsImF1ZCI6WyJodHRwczovL3R0LWlkZW50aXR5c2VydmVyNC1kZW1vLmF6dXJld2Vic2l0ZXMubmV0L3Jlc291cmNlcyIsImFwaSJdLCJjbGllbnRfaWQiOiJyZXNvdXJjZW93bmVyIiwic3ViIjoiODg0MjExMTMiLCJhdXRoX3RpbWUiOjE1NDQ0NjcxNDUsImlkcCI6ImxvY2FsIiwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsImFwaSJdLCJhbXIiOlsicHdkIl19.Gaso6tfCX9WTSsoPi1NfOuK4NkPPRiVdWZfbdCP64MZzRAzdf-gpa_MHGnqiUbzxte-Uj_X24X0WE4MjnU_u6kPUu01boFU8cSjwtg-dfPics1OLpZnLetqIR6wbjwLqTKbHPPlKJ_-4h74bYugB0rDpXEHNzC21P16XTfoeGkeaMpfTD4fJ5DXw3bOPiOjfnhj2kHUHs1SAkHP-EfR3X0PJyCML7PQUKeRWhEsoI8Uryr17FCgxMscKM-rKjZkMuAFabQegsfxm7PuZEHWAkhOGiA1_kRMcw9TGT4Za6sjYv39YpZ8gl877e4KC1m9ut2L0qT9LbrB3F5l1189qfg

POST http://localhost:7071/api/orders
#POST https://orders.serverlessmicroservices.net/api/orders
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "description": "Order for Foo",
  "items": [
    {
      "id": "a5e05e3a-5c7d-4993-bf86-aa22554d91d2",
      "quantity": 2
    }
  ]
}