# Regularly update the token via the RetrieveToken.http script
@token = Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjljNTIxMGFiZWZmZTg2ZjlkMmI5ZTEzM2Q4NWNjZDA4IiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NDU1ODk3OTUsImV4cCI6MTU0NTY3NjE5NSwiaXNzIjoiaHR0cHM6Ly90dC1pZGVudGl0eXNlcnZlcjQtZGVtby5henVyZXdlYnNpdGVzLm5ldCIsImF1ZCI6WyJodHRwczovL3R0LWlkZW50aXR5c2VydmVyNC1kZW1vLmF6dXJld2Vic2l0ZXMubmV0L3Jlc291cmNlcyIsImFwaSJdLCJjbGllbnRfaWQiOiJyZXNvdXJjZW93bmVyIiwic3ViIjoiODg0MjExMTMiLCJhdXRoX3RpbWUiOjE1NDU1ODk3OTUsImlkcCI6ImxvY2FsIiwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsImFwaSJdLCJhbXIiOlsicHdkIl19.WgFFsJkqUg5D39e_4a3jes-tz-i6vkGu5xK3OOMKovokMLn_ICEBadrBiPlZC_QzxP0SuNooq1TAcAfDG-ZNgun5JYwikULih-R5Oueqa89rK7I9Ts8F1gQMLKgIpH1eszRgNa7XCGqEzZTCj1oPCybMgPKiICPw1RXsooMqKXQPv4fEVTFNPf21hbqDqncVFFtewF2FxrV3Sh9e-yHGa-QAeXg-oCOtMHaxljlpw3feD2UHj_bGIFNR1uUAS7AMneVGaiQ3No6TCn1j49EVe6y5MFAoX7Zf_k0JJqMB3wUjcalcHphttbbnJFFJuv6AgjYPTRXMpylJHLpXcikN5g

POST http://localhost:7071/api/orders
#POST https://orders.serverlessmicroservices.net/api/orders
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "description": "Order for Valentin",
  "items": [
    {
      "id": "906625b2-2aa8-4799-9a86-dd98b577b681",
      "quantity": 2
    }
  ]
}